### ISSUE TITLE
The requested resource could not be found.

### ISSUE THREAD

**Issue by mischief24** [i13-msrg/vibes#2]
hi
I'm trying to run your simulator. I've noticed a problem - when I start simulation then get error
[ERROR] [09/16/2018 17:57:26.021] [VSystem-akka.actor.default-dispatcher-8] [akka://VSystem/user/Master/Reducer] null
java.util.NoSuchElementException
	at scala.collection.LinearSeqOptimized.last(LinearSeqOptimized.scala:146)
	at scala.collection.LinearSeqOptimized.last$(LinearSeqOptimized.scala:145)
	at scala.collection.immutable.List.last(List.scala:86)
	at com.vibes.actors.ReducerActor$.calculateResult(ReducerActor.scala:123)
	at com.vibes.actors.ReducerActor$$anonfun$receive$1.applyOrElse(ReducerActor.scala:25)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at com.vibes.actors.ReducerActor.aroundReceive(ReducerActor.scala:10)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

http://localhost:8082/ - I have "The requested resource could not be found."
Do you have any proposition how to solve that?

**Comment by FabianSchuessler** [comment]
Thank you for your feedback and for trying out the simulator.

You were trying to access the backend without a valid list of parameters. http://localhost:8082 is the backend. If you access the backend with a valid list of parameters then you will get the simulation results in plain data.

Please try to access the frontend via http://localhost:8080/. The frontend will create a valid parameter list according to your wishes and will visualize the results.

If you are using Windows, the "start frontend and backend.bat" script will automatically open the frontend for you.

**Comment by mischief24** [comment]
Thanks for the answer.
I'm just sorry that it took so long.I think that I didn't describe my problem first time.
I'm using Linux system. Both part are running (backend and frontend). I was on "master" branch.
Now, I've changed as you said to FabianSchuessler.
When I go directly to backend part (http://localhost:8082/) I have: The requested resource could not be found (and I guess is a correct behaviour).
When I'm using frontend part and generate blockchain simulation with default values, just to verify:
![image](https://user-images.githubusercontent.com/17409731/45925889-b6679a80-bf1d-11e8-8d4e-29fa107ea541.png)
then I have errors in console (completely different than week ago)
![image](https://user-images.githubusercontent.com/17409731/45925912-f62e8200-bf1d-11e8-9982-cf23a91c75a8.png)

**Comment by mischief24** [comment]
Ok problem solved with d3.js ;)
On FabianSchuessler branch - the simulation looks like it works.
Thx again

**Comment by FabianSchuessler** [comment]
I am glad I could help you. Feel free to ask me any questions.

In your screenshot you were using the "generic simulation", I recommend you to also try the "bitcoin-like blockchain simulation" with more configurable options and attack scenarios.
